### ISSUE TITLE
Ask the user if he wants to add the custom layout before save to file

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton#290]
---

Author Name: **Felipe Cecagno** (Felipe Cecagno)
Original Redmine Issue: 1827, http://dev.mconf.org/redmine/issues/1827
Original Date: 2015-10-23

---

If the user saves the layouts to file, only the layouts added to the list are saved. If the user is using a custom layout, that one isn't going to be saved. Ask the user "Include the current layout?", then let him name it, and then save it to file.

**Comment by fcecagno** [comment]
Implemented by @RafaFP here: https://github.com/RafaFP/bigbluebutton/tree/feature-1827

It can be simplified. There's no need to create a new TitleWindow just to get an answer from the user. You can implement something similar to what we have when the user hit the quit button or the record button.
