### ISSUE TITLE
Button to download presentations should only be enabled if there's at least one presentation to download

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton#296]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1851, http://dev.mconf.org/redmine/issues/1851

---

If there are no presentations available to download, the button to download presentations should be disabled and have a tooltip saying that "there are no presentations available for download".

**Comment by fcecagno** [comment]
Merged.
