### ISSUE TITLE
Weird scrollbars when downloading presentations with big names

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton#297]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1852, http://dev.mconf.org/redmine/issues/1852

---

See the image attached.
It doesn't happen in the upload dialog, only when downloading.

**Comment by mconf-daileon** [comment]
---

Original attachments:
- [screenshot from 2015-11-05 16_27_57](https://cloud.githubusercontent.com/assets/1714273/15054651/eecd2cde-12de-11e6-867a-360956e8b6c8.png)

---

**Comment by RafaFP** [comment]
Solution was implemented here.

https://github.com/RafaFP/bigbluebutton/tree/fix-1852

**Comment by fcecagno** [comment]
Merged.
