### ISSUE TITLE
Mute sound icon

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton#299]
---

Author Name: **Kent Borjesjo** (Kent Borjesjo)
Original Redmine Issue: 1894, http://dev.mconf.org/redmine/issues/1894
Original Date: 2016-01-05

---

Mute sound icon

Would be great to have back the mute sound icon at the top bar, where it where earlier, I thing 5.2 or even 4.3.

**Comment by fcecagno** [comment]
We have no plans to implement this.
