### ISSUE TITLE
Multiple RTMP deskshare streams

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton#301]
---

Author Name: **Felipe Cecagno** (Felipe Cecagno)
Original Redmine Issue: 1910, http://dev.mconf.org/redmine/issues/1910
Original Date: 2016-01-14
Original Assignee: Pedro Beschorner Marin

---

The current RTMP deskshare streams handling on the Red5 Deskshare app doesn't work when there are multiple deskshare streams (it's always one per room, but could be multiple rooms running). This is all because of this: https://github.com/fcecagno/bigbluebutton/blob/deskshare-rtmp/deskshare/app/src/main/scala/org/bigbluebutton/deskshare/server/red5/DeskshareApplication.scala#L217

Imagine the scenario:
- start stream A
- start stream B
  (here customRtmpStream = stream B)
- stop stream A
  (here stream B will be stopped)
- stop stream B
  (here stream A will remain running, while stream B will be stopped again - might throw an exception)

We need a smarter way to handle these streams.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Pedro Beschorner Marin** (Pedro Beschorner Marin)
Original Date: 2016-01-15T14:48:29Z

---

Tested with 4 RTMP streams using ffmpeg:
$ ffmpeg -re -ignore_loop 0 -i GIF_IMAGE -profile:v baseline -vcodec libx264 -f flv "rtmp://SERVER_IP/deskShare/ROOM_NAME"

Global variable customRtmpStream is overwritten so the problem exists. Fixed storing those streams in a HashMap structure.

https://github.com/pedrobmarin/bigbluebutton/commit/098b9ab0e2f84d9b160b8aca2d6e4cd11f1d8482

**Comment by fcecagno** [comment]
Merged.
