### ISSUE TITLE
Recording of RTMP deskshare streams

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton#302]
---

Author Name: **Felipe Cecagno** (Felipe Cecagno)
Original Redmine Issue: 1911, http://dev.mconf.org/redmine/issues/1911
Original Date: 2016-01-14
Original Assignee: Pedro Beschorner Marin

---

The recording process of deskshare streams is done during the transcoding of HTTP to RTMP streaming. It means that if we stream RTMP directly to the deskshare app, it won't be recorded. We have to implement something similar to what we do on bbb-video: https://github.com/fcecagno/bigbluebutton/blob/deskshare-rtmp/bbb-video/src/main/java/org/bigbluebutton/app/video/VideoApplication.java#L189

If we use the same name conventions the HTTP deskshare does, the record and playback will work out of the box.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Pedro Beschorner Marin** (Pedro Beschorner Marin)
Original Date: 2016-01-20T19:58:15Z

---

Recording RTMP stream FLV file in /var/bigbluebutton/deskshare and sending redis' start, stop and error events.

https://github.com/pedrobmarin/bigbluebutton/tree/deskshare-rtmp

Only tested with ffmpeg sending the RTMP stream: $ ffmpeg -re -ignore_loop 0 -i GIF_FILE -profile:v high444 -vcodec libx264  -f flv "rtmp://SERVER_IP/deskShare/ROOM"
Need to be tested with a client sending the RTMP stream.

**Comment by fcecagno** [comment]
Merged.
