### ISSUE TITLE
Chat messages should use the server clock, not the user clock

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton#303]
---

Author Name: **Felipe Cecagno** (Felipe Cecagno)
Original Redmine Issue: 1915, http://dev.mconf.org/redmine/issues/1915
Original Date: 2016-01-19
Original Assignee: Felipe Cecagno

---

It would avoid the scenario of the screenshot attached, where the message sent at 14:07 is displayed before messages sent at 14:02.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Rafael Petersen** (Rafael Petersen)
Original Date: 2016-02-15T19:15:59Z

---

Fixed the issue of the out of order timestamps by using the getTime function on the server.
Server time will be used. It will be displayed adapted for each user's timezone on client chat window.

link to the fix compare: https://github.com/mconf/bigbluebutton/compare/mconf...RafaFP:fix-1915?expand=1

**Comment by mconf-daileon** [comment]
---

Original attachments:
- [imgpsh_fullsize](https://cloud.githubusercontent.com/assets/1714273/15083933/9aa08660-13a6-11e6-805d-4b121829c4a8.png)

---

**Comment by pedrobmarin** [comment]
Hi @RafaFP, how may I test this?

**Comment by RafaFP** [comment]
If you just use three diferent computers (server and two clients) that are each set with diferent timezones and then start sending messages then the click on each message should be always increasing - if the user the user who is some hours behind sends a message it should not have the clock showing a time earlyer than other messages sent by the other user.

**Comment by fcecagno** [comment]
Merged.
