### ISSUE TITLE
Speedup getRecordings

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton#306]
---

Author Name: **Felipe Cecagno** (Felipe Cecagno)
Original Redmine Issue: 1921, http://dev.mconf.org/redmine/issues/1921
Original Date: 2016-01-25
Original Assignee: Pedro Beschorner Marin

---

The getRecordings call can be very slow depending on the number of recordings in the server.

A preliminary work has been done here: https://github.com/fcecagno/bigbluebutton/tree/speedup-getrecordings
However, it looks like the slow part is not the retrieval of the metadata values from the file system, but the way we render the XML - we can very easily keep track on the time consumption on each phase of the getRecordings handling.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Pedro Beschorner Marin** (Pedro Beschorner Marin)
Original Date: 2016-01-27T18:22:29Z

---

Added FreeMarker lib (http://freemarker.incubator.apache.org/) and building get-recordings XML response with it.

https://github.com/pedrobmarin/bigbluebutton/tree/speedup-getrecordings

**Comment by mconf-daileon** [comment]
---

Original attachments:
* [all-metadata.zip](https://github.com/mconf/bigbluebutton/files/252921/all-metadata.zip)
* [get_recordings performance test.txt](https://github.com/mconf/bigbluebutton/files/252922/get_recordings.performance.test.txt)

---

**Comment by fcecagno** [comment]
Done!
