### ISSUE TITLE
Add a button for the moderator to be able to clear the chat window history. 

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton#311]
---

Author Name: **Rafael Petersen** (Rafael Petersen)
Original Redmine Issue: 1931, http://dev.mconf.org/redmine/issues/1931
Original Date: 2016-02-17
Original Assignee: Felipe Cecagno

---

Add a button for moderators to be able to clear the chat window, removing all the messages from the server and clearing it for all current users and future conference joiners.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Rafael Petersen** (Rafael Petersen)
Original Date: 2016-02-23T20:34:06Z

---

Implemented a button to clear chat history.
New conversation joiners will not receive the history previous to the clearing.
Current conversation users will clear the local chat history and be notified that a moderator cleared the chat.
Implemented a Warning PopUp Window to check that the moderator really wants to clear the chat.

link to the compare: https://github.com/mconf/bigbluebutton/compare/mconf...RafaFP:feature-1931?expand=1

**Comment by mconf-daileon** [comment]
---

Original attachments:
- [test1](https://cloud.githubusercontent.com/assets/1714273/15083924/88978f7c-13a6-11e6-9060-014cd1bf27f3.png)
- [test2](https://cloud.githubusercontent.com/assets/1714273/15083923/88961c96-13a6-11e6-8672-ae73c69b4c69.png)

---

**Comment by fcecagno** [comment]
Implemented and merged on branch mconf
