### ISSUE TITLE
Offer an option for the moderator to end the meeting when he leaves the room

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton#314]
---

Author Name: **Rafael Petersen** (Rafael Petersen)
Original Redmine Issue: 1944, http://dev.mconf.org/redmine/issues/1944
Original Date: 2016-03-18
Original Assignee: Felipe Cecagno

---

The moderators should be able to choose to end the meeting when they leave the room.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Kent Borjesjo** (Kent Borjesjo)
Original Date: 2016-03-18T19:40:20Z

---

Rafael Petersen wrote:

> The moderators should be able to choose to end the meeting when they leave the room.

Appreciate that, so often some or even one  forget to leave the room and the meeting can be open for hours.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Rafael Petersen** (Rafael Petersen)
Original Date: 2016-03-29T21:16:57Z

---

Implemented a button to give moderators the option to end the meeting when they logout.
The meeting will be closed as soon as the moderator presses the button to confirm logout and end meeting.
All users will be logged out and no on will be able to join the meeting after this moment.
The meeting is still visible from the API (getMeetings) for a few seconds after the moderator gives this command, but will be inaccessible and soon removed.

link to the compare: https://github.com/mconf/bigbluebutton/compare/mconf...RafaFP:feature-1944?expand=1

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Rafael Petersen** (Rafael Petersen)
Original Date: 2016-03-30T20:15:02Z

---

Reviewing the way that the API endMeeting command works in order to make the client and API follow the same path and perform consistently.

**Comment by mconf-daileon** [comment]
---

Original Redmine Comment
Author Name: **Rafael Petersen** (Rafael Petersen)
Original Date: 2016-03-30T21:30:09Z

---

The changes made to bigbluebutton-web MeetingService.java now cause the API end command and the moderator's client command to behave in the same way.
The delay in removing meeting info and start recording processing will no longer be observed.

link to the compare: https://github.com/mconf/bigbluebutton/pull/33/files

**Comment by fcecagno** [comment]
Merged on brach mconf.
