### ISSUE TITLE
Empty button at presentation window

### ISSUE THREAD

**Issue by pedrobmarin** [mconf/bigbluebutton#328]
This happens when the presenter removes from the meeting the current presentation and gives the presenter role to other participant. To the new presenter will be shown an empty button right after the download/upload buttons.

**Comment by pedrobmarin** [comment]
fixed on this commit: https://github.com/pedrobmarin/bigbluebutton/commit/0a802d63db296d6b5ce64c92124abf68a4b1baf7

**Comment by fcecagno** [comment]
Merged on branch mconf.
