### ISSUE TITLE
Add missing information to redis events for recordings

### ISSUE THREAD

**Issue by daronco** [mconf/bigbluebutton#336]
The events related to recordings that are published to redis are currently not enough for an integration to recreate all the information of a recording just by listening to these events using the webhooks. If the integration uses the `getRecordings` API call, it will receive more data.

The idea is that an integration should have all information it currently has if it calls `getRecordings` by just listening to the recording events using the webhooks.

What should be added/changed is:
- All events for recordings should have the record ID, the internal meeting ID and the external meeting ID. They currently have only the internal meeting ID (that is labelled as `meeting_id`).
- The event `publish_ended` includes most of the information of a recording, such as the metadata, the playback options, etc. Some things should be changed in this event:
  - Add information that is missing: `name`, `startTime`, `endTime`, `size`, `rawSize`. These should all have the same values returned by `getRecordings`.
  - Inside the playback and download formats, add `length`(that is also returned by `getRecordings`).
  - Inside the playback and download formats, consider renaming `link` to `url`, because this is how it's returned by `getRecordings`. This is minor and I'm not sure how it will work with the rest of the code that uses this event.

**Comment by pedrobmarin** [comment]
About your considerations:
- record_id: The internal meeting ID and the record ID have the same value. Should we replicate this data in the events?
- publish_ended: The publish_ended event already have the size field within the playback information, can you confirm if this is one of the informations you are asking for?
- length: There is a 'duration' information in the playbacks, the thing is bbb-web transform this value from milis to minutes when responding the API call.
- url: I have no idea who uses this events, maybe @fcecagno can tell if it is OK to change this with no concerns.

Besides those considerations I made the changes you needed. Now recording events will also have the external_meeting_id:

```
1474475244.995001 [0 127.0.0.1:60210] "publish" "bigbluebutton:from-rap" "{\"header\":{\"timestamp\":15605269,\"name\":\"archive_ended\",\"current_time\":1474475244,\"version\":\"0.0.1\"},\"payload\":{\"success\":true,\"step_time\":755,\"external_meeting_id\":\"random-6778996\",\"meeting_id\":\"50f637b658dcfebf958f6c1cf2326dc6c62a3c7e-1474475168797\"}}"
```

and publish_ended will look like this:

```
1474475255.162613 [0 127.0.0.1:60210] "publish" "bigbluebutton:from-rap" "{\"header\":{\"timestamp\":15615437,\"name\":\"publish_ended\",\"current_time\":1474475255,\"version\":\"0.0.1\"},\"payload\":{\"success\":true,\"step_time\":830,\"playback\":{\"format\":\"presentation\",\"link\":\"http://10.0.3.221/playback/presentation/0.9.0/playback.html?meetingId=50f637b658dcfebf958f6c1cf2326dc6c62a3c7e-1474462703710\",\"processing_time\":8126,\"duration\":6654,\"size\":167577},\"metadata\":{\"meetingId\":\"random-6778996\",\"meetingName\":\"random-6778996\"},\"download\":{},\"raw_size\":470689,\"start_time\":1474462703710,\"end_time\":1474462726979,\"workflow\":\"presentation\",\"external_meeting_id\":\"random-6778996\",\"meeting_id\":\"50f637b658dcfebf958f6c1cf2326dc6c62a3c7e-1474462703710\"}}"
```

And let's discuss about the results and considerations.
Here is the link to the branch with the modifications https://github.com/pedrobmarin/bigbluebutton/tree/recording-events-improvments
